### PR TITLE
WIP - first integration with gogo juju and MaaS

### PR DESCRIPTION
**Pull request by oneilcin**
We successfully created a cluster, checked cluster status, updated the kubeconfig, and deleted a cluster in MaaS.  This contains hardcoding for MaaS right now.  We also discovered some blocking when creating the juju controller (about 4 minutes) that needs attention (the controller is needed for other gogo commands).

### CODE REVIEW

**Comment by alejandroEsc** [comment]
where are the unit tests?

**Comment by joejulian** [comment]
@alejandroEsc Tests will come after we have finished ensuring we make the deadline.

**Comment by alejandroEsc** [comment]
@joejulian simple tests are not something that block deadlines, i wouldnt consider that ok.

**Comment by alejandroEsc** [comment]
also after deadline this is not going to be reused again, right? so why even have tests then?

**Comment by alejandroEsc** [comment]
@joejulian and myself agreed I would write a few tests to help out on this part and to help the team orient themselves writing tests as they see fit in the future.

**Comment by oneilcin** [comment]
I can add a few simple ones

On Tue, May 1, 2018 at 10:37 AM, Alejandro Escobar <notifications@github.com

**Comment by alejandroEsc** [comment]
was this meant to be merged? it has WIP in title??

**Comment by joejulian** [comment]
It was. We talked offline. I should have mentioned that in the comments.

**Pull request merged**
