### PR TITLE
testing this dir structure with CI

### PR DESCRIPTION
**Pull request by leahnp**
Testing to see if this dir structure will work with CI

*Note- if we merge this we will need to update the package import links

### CODE REVIEW

**Comment by alejandroEsc** [comment]
I am wondering what this means? I can see there was some packaging/dep changes, could we hold off on those types of changes until we make a move to dep?

**Comment by leahnp** [comment]
@alejandroEsc not sure exactly what your are referring to by "this" - I posted some more general info on this PR in our slack channel.  Let me know if it makes more sense after this.

**Comment by alejandroEsc** [comment]
@leahnp this=`Testing to see if this dir structure will work with CI

*Note- if we merge this we will need to update the package import links`

**Comment by leahnp** [comment]
@alejandroEsc ok - do you feel like the conversation in Slack filled in the gaps? Let me know if you have any other questions. I don't have a preference on dir structure, I just wanted the team to be able to see how CI dictates it should be (with this PR). We need to make a decision as a team what direction to go from here.

**Comment by alejandroEsc** [comment]
@leahnp Let's go ahead and make the suggested changes so as to keep the directory structure as what go standards dictate. If you cant do that at this point let me know so we can coordinate and get whatever you need to finish this task.

**Comment by leahnp** [comment]
Closing because CI was updated to accommodate build contexts outside of rootfs/project/

**Pull request closed without merging**
